# Generated by Django 4.2 on 2023-05-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacija', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogadjaj',
            name='prodaje_se',
            field=models.ManyToManyField(db_table='prodaje_se', to='Aplikacija.prodajnomesto'),
        ),
    ]
