# Generated by Django 4.2 on 2023-05-23 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacija', '0002_dogadjaj_prodaje_se'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muzika',
            fields=[
                ('dogadjaj_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Aplikacija.dogadjaj')),
                ('izvodjac', models.CharField(max_length=50)),
            ],
            bases=('Aplikacija.dogadjaj',),
        ),
        migrations.CreateModel(
            name='Ostalo',
            fields=[
                ('dogadjaj_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Aplikacija.dogadjaj')),
            ],
            bases=('Aplikacija.dogadjaj',),
        ),
        migrations.CreateModel(
            name='Pozoriste',
            fields=[
                ('dogadjaj_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Aplikacija.dogadjaj')),
                ('zanr', models.CharField(max_length=50)),
                ('glumci', models.CharField(max_length=100)),
                ('trajanje', models.DurationField()),
            ],
            bases=('Aplikacija.dogadjaj',),
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('dogadjaj_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Aplikacija.dogadjaj')),
                ('naziv_sporta', models.CharField(max_length=50)),
                ('ucesnici', models.CharField(max_length=100)),
            ],
            bases=('Aplikacija.dogadjaj',),
        ),
        migrations.CreateModel(
            name='Zurka',
            fields=[
                ('dogadjaj_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Aplikacija.dogadjaj')),
                ('vrsta_muzike', models.CharField(max_length=50)),
                ('izvodjac', models.CharField(max_length=50, null=True)),
            ],
            bases=('Aplikacija.dogadjaj',),
        ),
    ]
