# Generated by Django 4.2 on 2023-05-23 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacija', '0004_alter_muzika_table_alter_ostalo_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('pitanje', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recenzija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField()),
                ('komentar', models.CharField(max_length=150)),
                ('dogadjaj', models.ForeignKey(db_column='idDog', on_delete=django.db.models.deletion.CASCADE, to='Aplikacija.dogadjaj')),
                ('korisnik', models.ForeignKey(db_column='idKor', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recenzija',
            },
        ),
    ]
