# Generated by Django 4.2 on 2023-05-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacija', '0005_upit_recenzija'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='upit',
            table='upit',
        ),
    ]
