# Generated by Django 4.2 on 2023-05-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacija', '0006_alter_upit_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadjaj',
            name='opis',
            field=models.CharField(max_length=600),
        ),
    ]
