# Generated by Django 4.2.1 on 2023-05-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacija', '0007_alter_dogadjaj_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
